export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  dashboard: {
    overview: '/dashboard/overview',
    sales: '/dashboard/sales',
    customers: '/dashboard/customers',
    products: '/dashboard/products',
    inventory: '/dashboard/inventory',
    orders: '/dashboard/orders',
    charts: {
      revenue: '/dashboard/charts/revenue',
      orders: '/dashboard/charts/orders',
      customers: '/dashboard/charts/customers',
      products: '/dashboard/charts/products',
      inventory: '/dashboard/charts/inventory',
    },
  },
  users: '/users',
  roles: '/roles',
  permissions: '/permissions',
  customers: '/customers',
  products: '/products',
  categories: '/categories',
  inventory: {
    base: '/inventory',
    increase: '/inventory/increase',
    decrease: '/inventory/decrease',
    adjust: '/inventory/adjust',
    transactions: '/inventory/transactions',
    analytics: '/inventory/analytics',
    lowStock: '/inventory/low-stock',
    outOfStock: '/inventory/out-of-stock',
    reorderProducts: '/inventory/reorder-products',
  },
  suppliers: '/suppliers',
  purchaseOrders: '/purchase-orders',
  orders: '/orders',
  quotations: '/quotations',
  invoices: '/invoices',
  payments: '/payments',
  expenses: {
    base: '/expenses',
    analytics: '/expenses/analytics',
  },
  expenseCategories: '/expense-categories',
  finance: {
    dashboard: '/finance/dashboard',
    profitLoss: '/finance/profit-loss',
    revenueBreakdown: '/finance/revenue-breakdown',
    expenseBreakdown: '/finance/expense-breakdown',
  },
  analytics: {
    overview: '/analytics/overview',
    revenue: '/analytics/revenue',
    expenses: '/analytics/expenses',
    profit: '/analytics/profit',
    customers: '/analytics/customers',
    projects: '/analytics/projects',
    tasks: '/analytics/tasks',
    topCustomers: '/analytics/top-customers',
    recentActivity: '/analytics/recent-activity',
  },
  reports: {
    businessSummary: '/reports/business-summary',
    revenue: '/reports/revenue',
    expenses: '/reports/expenses',
    profitLoss: '/reports/profit-loss',
    customers: '/reports/customers',
    projects: '/reports/projects',
    tasks: '/reports/tasks',
    invoice: '/reports/invoice',
    history: '/reports/history',
    historyDownload: '/reports/history',
    historyRegenerate: '/reports/history',
  },
  auditLogs: '/audit-logs',
  notifications: {
    base: '/notifications',
    preferences: '/notifications/preferences',
    readAll: '/notifications/read-all',
  },
  settings: {
    base: '/settings',
    businessProfile: '/settings/business-profile',
  },
  system: {
    health: '/system/health',
    stats: '/system/stats',
    environment: '/system/environment',
  },
} as const;

export const HTTP_HEADERS = {
  tenantId: 'X-Tenant-ID',
  authorization: 'Authorization',
  contentType: 'Content-Type',
} as const;

export const RETRY_CONFIG = {
  maxRetries: 2,
  delayMs: 1000,
  retryableStatuses: [408, 429, 502, 503, 504],
} as const;
