/** Central route path registry for the Angular SPA */
export const ROUTES = {
  root: '/',
  dashboard: '/dashboard',
  auth: {
    base: '/auth',
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyEmail: '/auth/verify-email',
  },
  onboarding: {
    base: '/onboarding',
    business: '/onboarding/business',
    owner: '/onboarding/owner',
    address: '/onboarding/address',
    currencyTax: '/onboarding/currency-tax',
    invoicePreferences: '/onboarding/invoice-preferences',
    logo: '/onboarding/logo',
    review: '/onboarding/review',
  },
  users: '/users',
  roles: '/roles',
  permissions: '/permissions',
  customers: '/customers',
  products: {
    base: '/products',
    list: '/products',
    create: '/products/new',
    detail: '/products/:id',
    edit: '/products/:id/edit',
    categories: {
      list: '/products/categories',
      create: '/products/categories/new',
      edit: '/products/categories/:id/edit',
    },
  },
  inventory: {
    base: '/inventory',
    overview: '/inventory/overview',
    stockLevels: '/inventory/stock-levels',
    history: '/inventory/history',
    reports: '/inventory/reports',
    dashboard: '/inventory/dashboard',
  },
  suppliers: {
    base: '/suppliers',
    list: '/suppliers',
    create: '/suppliers/new',
    detail: '/suppliers/:id',
    edit: '/suppliers/:id/edit',
  },
  purchaseOrders: {
    base: '/purchase-orders',
    list: '/purchase-orders',
    create: '/purchase-orders/new',
    detail: '/purchase-orders/:id',
    edit: '/purchase-orders/:id/edit',
  },
  orders: '/orders',
  invoices: '/invoices',
  reports: '/reports',
  settings: '/settings',
  profile: '/profile',
  forbidden: '/forbidden',
  notFound: '/not-found',
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
